version: '3'
services:
  chat-with-data:
    image: chat-with-data:latest
    build: .
    ports:
    - 8000:8000
    working_dir: /home/appuser/app/
    command: ["streamlit", "run", "/home/appuser/app/demo_apps/main.py"]
